### ISSUE TITLE
module fails to load after upgrade to 3.1.0

### ISSUE THREAD

**Issue by cbrandlehner** [CANDY-LINE/node-red-contrib-generic-ble#33]
from the Node-red log:

`May 20 10:34:23 rpi3 Node-RED[801]: 20 May 10:34:23 - [warn] [node-red-contrib-generic-ble/generic-ble] Error: Cannot find module '../../node_modules/@abandonware/noble/lib/noble'`

**Comment by cbrandlehner** [comment]
Update:
The problem occured after updating from 3.1.0 to 4.0.0

**Comment by cbrandlehner** [comment]
I did the following to restore:
`
rm -r node_modules/node-red-contrib-generic-ble/
npm install node-red-contrib-generic-ble@3.1.0
`

old version 3.1.0 is working fine.

**Comment by dbaba** [comment]
Thank you for the report. Fixed the issue and published v4.0.1.
