### ISSUE TITLE
Cannot find module @abandonware/noble/lib/resolve-bindings

### ISSUE THREAD

**Issue by radionoise** [CANDY-LINE/node-red-contrib-generic-ble#34]
Not working on macOS Catalina 10.15.5
```
17 Jun 15:30:56 - [info] Node-RED version: v1.0.6
17 Jun 15:30:56 - [info] Node.js  version: v12.12.0
17 Jun 15:30:56 - [info] Darwin 19.5.0 x64 LE
17 Jun 15:30:56 - [info] Loading palette nodes
17 Jun 15:30:57 - [warn] ------------------------------------------------------
17 Jun 15:30:57 - [warn] [node-red-contrib-generic-ble/generic-ble] Error: Cannot find module '../../node_modules/@abandonware/noble/lib/resolve-bindings'
Require stack:
- /Users/radionoise/.node-red/node_modules/node-red-contrib-generic-ble/dist/noble/index.js
- /Users/radionoise/.node-red/node_modules/node-red-contrib-generic-ble/dist/generic-ble.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/local/lib/node_modules/node-red/lib/red.js
- /usr/local/lib/node_modules/node-red/red.js
```

**Comment by dbaba** [comment]
Thanks for the report. Just published the bug fix (4.0.2).
Re-open the issue when you still see the same error.
